name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Install anaconda
      run: |
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
        bash ~/miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda install nomkl numpy scipy matplotlib
        pip install corner

    - name: Install kima and pykima
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"

        make -j 4
        python setup.py install


    # - name: Start the tests
    #   run: |
    #     pwd
    #     cd tests/test_suite

    - name: Run 51Peg example
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"
        cd tests/test_suite
        cp OPTIONS ../../examples/51Peg/OPTIONS
        kima-run ../../examples/51Peg -s 43
        # test the output
        cmp 51Peg_sample_seed43.txt ../../examples/51Peg/sample.txt

    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
